ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.devrats.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/devrats"
    url = ${?DATABASE_URL}
    user = "postgres"
    user = ${?DATABASE_USER}
    password = "devrats123"
    password = ${?DATABASE_PASSWORD}
}

github {
    clientId = "Iv23li2hgMfUstRiEY5I"
    clientSecret = """32298352b5ad28a1fc220244c1ae96b0a316c1e8"""
    webhookSecret = "devrats-webhook-secret"
}
