ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.devrats.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/devrats"
    url = ${?DATABASE_URL}
    user = "postgres"
    user = ${?DATABASE_USER}
    password = "devrats123"
    password = ${?DATABASE_PASSWORD}
}

github {
    clientId = "Iv23li2hgMfUstRiEY5I"
    clientSecret = """v9xQ2m#Lp$8sK!zR4w@Tn7Yc%Fh3b^Jd"""
    webhookSecret = "devrats-webhook-secret"
}
